Repository neoml-lib/neoml, pull requests merged in 2024-08, with the labels that each got.

#1 True C-interface for the NeoProxy.h
  NeoProxy/include/NeoProxy/NeoProxy.h
  NeoProxy/src/NeoProxy.cpp
Labels: refactor

#458 Allow passing const data to clustering functions
  NeoML/docs/en/API/Clustering/FirstCome.md
  NeoML/docs/en/API/Clustering/Hierarchical.md
  NeoML/docs/en/API/Clustering/ISODATA.md
  NeoML/docs/en/API/Clustering/README.md
  NeoML/docs/en/API/Clustering/kMeans.md
  NeoML/docs/ru/API/Clustering/FirstCome.md
  NeoML/docs/ru/API/Clustering/Hierarchical.md
  NeoML/docs/ru/API/Clustering/ISODATA.md
  NeoML/docs/ru/API/Clustering/README.md
  NeoML/docs/ru/API/Clustering/kMeans.md
  NeoML/include/NeoML/TraditionalML/Clustering.h
  NeoML/include/NeoML/TraditionalML/FirstComeClustering.h
  NeoML/include/NeoML/TraditionalML/HierarchicalClustering.h
  NeoML/include/NeoML/TraditionalML/IsoDataClustering.h
  NeoML/include/NeoML/TraditionalML/KMeansClustering.h
  NeoML/src/TraditionalML/FirstComeClustering.cpp
  NeoML/src/TraditionalML/HierarchicalClustering.cpp
  NeoML/src/TraditionalML/IsoDataClustering.cpp
  NeoML/src/TraditionalML/KMeansClustering.cpp
  NeoML/test/src/ClusteringTest.cpp
Labels: refactor

#1100 [NeoMLTest] Bump version
  .github/workflows/codeql.yml
  Sources.txt
Labels: dependencies

#1066 [NeoMathEngine] Refactored MemoryEngine
  NeoMathEngine/include/NeoMathEngine/NeoMathEngine.h
  NeoMathEngine/src/CMakeLists.txt
  NeoMathEngine/src/CPU/CpuMathEngine.cpp
  NeoMathEngine/src/CPU/CpuMathEngine.h
  NeoMathEngine/src/CPU/CpuMathEngineDnnDistributed.cpp
  NeoMathEngine/src/GPU/CUDA/CudaMathEngine.cpp
  NeoMathEngine/src/GPU/CUDA/CudaMathEngine.cu
  NeoMathEngine/src/GPU/CUDA/CudaMathEngine.h
  NeoMathEngine/src/GPU/Metal/MetalMathEngine.h
  NeoMathEngine/src/GPU/Metal/MetalMathEngine.mm
  NeoMathEngine/src/GPU/Vulkan/VulkanMathEngine.cpp
  NeoMathEngine/src/GPU/Vulkan/VulkanMathEngine.h
  NeoMathEngine/src/GPU/Vulkan/VulkanMathEngineVectorMath.cpp
  NeoMathEngine/src/MathEngine.cpp
  NeoMathEngine/src/MemoryEngineMixin.cpp
  NeoMathEngine/src/MemoryEngineMixin.h
Labels: refactor

#1064 [NeoMathEngine] Refactored StackAllocators
  NeoML/Python/src/PyDnnBlob.cpp
  NeoMathEngine/include/NeoMathEngine/MemoryHandle.h
  NeoMathEngine/include/NeoMathEngine/MemoryHandle.inl
  NeoMathEngine/src/CMakeLists.txt
  NeoMathEngine/src/CPU/CpuMathEngine.cpp
  NeoMathEngine/src/GPU/CUDA/CudaMathEngine.cpp
  NeoMathEngine/src/GPU/CUDA/CudaMathEngine.cu
  NeoMathEngine/src/GPU/Metal/MetalMathEngine.mm
  NeoMathEngine/src/GPU/Vulkan/VulkanMathEngine.cpp
  NeoMathEngine/src/MathEngineDeviceStackAllocator.cpp
  NeoMathEngine/src/MathEngineDeviceStackAllocator.h
  NeoMathEngine/src/MathEngineHostStackAllocator.cpp
  NeoMathEngine/src/MathEngineHostStackAllocator.h
  NeoMathEngine/src/MathEngineStackAllocator.cpp
  NeoMathEngine/src/MathEngineStackAllocator.h
  NeoMathEngine/src/MemoryEngineMixin.cpp
  NeoMathEngine/src/MemoryEngineMixin.h
  NeoMathEngine/src/MemoryHandleInternal.h
  NeoMathEngine/src/MemoryPool.h
Labels: refactor

#1083 [NeoML] Remove code copy-paste, add comments
  NeoML/include/NeoML/Dnn/Dnn.h
  NeoML/include/NeoML/Dnn/DnnBlob.h
  NeoML/include/NeoML/Dnn/Layers/CompositeLayer.h
  NeoML/include/NeoML/Dnn/Layers/RecurrentLayer.h
  NeoML/src/Dnn/BaseLayer.cpp
  NeoML/src/Dnn/DnnBlob.cpp
  NeoMathEngine/include/NeoMathEngine/BlobDesc.h
Labels: refactor

#1103 [NeoML] CSparseMatrixDesc ctor
  NeoML/include/NeoML/Dnn/DnnSparseMatrix.h
  NeoML/src/Dnn/DnnSparseMatrix.cpp
  NeoML/src/TraditionalML/PCA.cpp
  NeoMathEngine/include/NeoMathEngine/SparseMatrixDesc.h
  NeoMathEngine/test/src/common/TestFixture.h
Labels: refactor

#484 Update installation docs
  NeoML/docs/en/Installation/cpp.md
  NeoML/docs/en/Installation/python_wrapper.md
  NeoML/docs/ru/Installation/cpp.md
  NeoML/docs/ru/Installation/python_wrapper.md
Labels: documentation
