Repository neoml-lib/neoml, pull requests merged in 2024-09, with the labels that each got.

#1102 [NeoML-Py] Fix CodeQL warnings
  NeoML/Python/CMakeLists.txt
  NeoML/Python/neoml/AutoDiff.py
  NeoML/Python/neoml/Blob.py
  NeoML/Python/neoml/Clustering.py
  NeoML/Python/neoml/CrossValidation.py
  NeoML/Python/neoml/DecisionTree.py
  NeoML/Python/neoml/Dnn/DnnDistributed.py
  NeoML/Python/neoml/Dnn/MultichannelLookup.py
  NeoML/Python/neoml/Dnn/SpaceAndDepth.py
  NeoML/Python/neoml/Dnn/Split.py
  NeoML/Python/neoml/Dnn/TiedEmbeddings.py
  NeoML/Python/neoml/Dnn/Transformer.py
  NeoML/Python/neoml/GradientBoost.py
  NeoML/Python/neoml/Linear.py
  NeoML/Python/neoml/PCA.py
  NeoML/Python/neoml/SVM.py
  NeoML/Python/neoml/Utils.py
  NeoML/Python/setup.py
  NeoML/Python/src/PyClustering.cpp
  NeoML/Python/src/PyDnnDistributed.cpp
  NeoML/Python/src/PyOnnxLayers.cpp
  NeoML/Python/src/PyPCA.cpp
  NeoML/Python/src/PyTiedEmbeddingsLayer.cpp
  NeoML/Python/src/PyTiedEmbeddingsLayer.h
  NeoML/Python/src/PyTrainingModel.cpp
  NeoML/Python/src/PyTransformLayer.cpp
  NeoML/Python/src/PyTransformerLayer.cpp
  NeoML/Python/src/PyTransformerLayer.h
  NeoML/Python/tests.py
  NeoML/docs/en/Python/conf.py
  NeoML/include/NeoML/Dnn/Layers/TiedEmbeddingsLayer.h
  NeoML/samples/python/boosting.py
  NeoML/src/Dnn/Layers/TiedEmbeddingsLayer.cpp
  NeoOnnx/test/Python/neoml_onnx_backend_test.py
Labels: dependencies, refactor

#1109 [NeoMLTest] Fix time prints
  NeoML/test/src/ClassificationAndRegressionTest.cpp
  NeoML/test/src/LoraTest.cpp
Labels: refactor

#566 [NeoML] JIT readme
  NeoMathEngine/src/CPU/x86/avx/src/docs/JIT.en.md
  NeoMathEngine/src/CPU/x86/avx/src/docs/JIT.ru.md
  NeoMathEngine/src/CPU/x86/avx/src/docs/RestOfLstm.pdf
Labels: documentation

#1106 [NeoML] CTiedEmbeddingsLayer is learnable with empty paramBlobs
  NeoML/include/NeoML/Dnn/Dnn.h
  NeoML/include/NeoML/Dnn/DnnSolver.h
  NeoML/include/NeoML/Dnn/Layers/ChannelwiseWith1x1Layer.h
  NeoML/include/NeoML/Dnn/Layers/MobileNetV2BlockLayer.h
  NeoML/include/NeoML/Dnn/Layers/MobileNetV3BlockLayer.h
  NeoML/include/NeoML/Dnn/Layers/TiedEmbeddingsLayer.h
  NeoML/src/Dnn/BaseLayer.cpp
  NeoML/src/Dnn/DnnSolver.cpp
  NeoML/src/Dnn/Layers/TiedEmbeddingsLayer.cpp
Labels: bug

#1107 [NeoML] CTiedEmbeddingsLayer extend functional interface
  NeoML/include/NeoML/Dnn/DnnLambdaHolder.h
  NeoML/include/NeoML/Dnn/Layers/TiedEmbeddingsLayer.h
  NeoML/src/Dnn/Layers/TiedEmbeddingsLayer.cpp
Labels: refactor

#1108 [NeoML] CLayerWrapper no limit connections
  NeoML/include/NeoML/Dnn/Dnn.h
  NeoML/include/NeoML/Dnn/Dnn.inl
Labels: refactor

#1112 [NeoMLTest] Add GraphGeneratorTest
  NeoML/include/NeoML/Dnn/DnnDistributed.h
  NeoML/test/src/CMakeLists.txt
  NeoML/test/src/GraphGeneratorTest.cpp
  Sources.txt
Labels: enhancement

#1113 [NeoMLTest] Add SpaceToDepth tests
  NeoML/test/src/CMakeLists.txt
  NeoML/test/src/DnnSimpleTest.h
  NeoML/test/src/DnnSimpleTests.cpp
  NeoML/test/src/SpaceToDepthTest.cpp
Labels: enhancement

#1117 [NeoMLTest] Fix CFloatHandleStackVar
  NeoML/src/Dnn/Layers/LossLayer.cpp
  NeoML/test/src/SpaceToDepthTest.cpp
  NeoMathEngine/src/GPU/Vulkan/VulkanMathEngineDnnConvs.cpp
  NeoMathEngine/test/src/inference/BlobMergeByDimTest.cpp
  NeoMathEngine/test/src/inference/VectorMultichannelLookupAndCopyTest.cpp
  NeoMathEngine/test/src/learn/TransposeMatrixTest.cpp
  NeoMathEngine/test/src/learn/VectorMultichannelLookupAndAddToTableTest.cpp
Labels: performance

#1116 [MetalMathEngine] Fix compilation
  NeoMathEngine/CMakeLists.txt
  NeoMathEngine/src/GPU/Metal/MetalMathEngine.h
  NeoMathEngine/src/GPU/Metal/MetalMathEngineBlas.mm
  NeoMathEngine/src/GPU/Metal/MetalMathEngineDnn.mm
  NeoMathEngine/src/GPU/Metal/MetalMathEngineDnnPoolings.mm
  NeoMathEngine/src/GPU/Metal/MetalMathEngineVectorMath.mm
  NeoMathEngine/src/MemoryPool.h
Labels: bug

#1121 [NeoMLTest] Rename sources
  NeoML/test/src/CMakeLists.txt
  NeoML/test/src/DnnBatchNormFusionTest.cpp
  NeoML/test/src/DnnChannelwiseWith1x1BlockTest.cpp
  NeoML/test/src/DnnCtcTest.cpp
  NeoML/test/src/DnnLambSolverTest.cpp
  NeoML/test/src/DnnLoraTest.cpp
  NeoML/test/src/DnnMobileNetV2BlockTest.cpp
  NeoML/test/src/DnnMobileNetV3BlockTest.cpp
  NeoML/test/src/DnnOnnxLayerTest.cpp
  NeoML/test/src/DnnOptimizationTest.cpp
  NeoML/test/src/DnnParameterLayerTest.cpp
  NeoML/test/src/DnnReferenceTest.cpp
  NeoML/test/src/DnnRowwiseTest.cpp
  NeoML/test/src/DnnSpaceToDepthTest.cpp
  NeoML/test/src/DnnTiedEmbeddingTest.cpp
  NeoML/test/src/DnnTransformerSourceMaskTest.cpp
Labels: refactor

#1119 [NeoMathEngine] Remove IMathEngine from MemoryHandleVar
  NeoMathEngine/include/NeoMathEngine/MemoryHandle.h
  NeoMathEngine/include/NeoMathEngine/MemoryHandle.inl
Labels: refactor

#1120 [NeoML] Sort fields by size to decrease the struct size
  NeoML/include/NeoML/Dnn/Dnn.h
  NeoML/src/Dnn/BaseLayer.cpp
  NeoML/src/Dnn/Dnn.cpp
Labels: performance

#1115 [NeoOnnx] Bump protobuf
  Build/Sources.ThirdParty.txt
  NeoML/Python/CMakeLists.txt
  NeoML/Python/setup.py
  NeoOnnx/src/CMakeLists.txt
  NeoOnnx/src/Operators/GatherOperator.cpp
  Sources.txt
Labels: dependencies
